"
"
"
" Environment {
    let mapleader = ','
    " Identify platform {
        silent function! OSX()
            return has('macunix')
        endfunction
        silent function! LINUX()
            return has('unix') && !has('macunix')
        endfunction
    " }

    " Basics {
        set nocompatible        " Must be first line
    " }
" }

" Use bundles config {
    if filereadable(expand("~/.vimrc.bundles"))
        source ~/.vimrc.bundles
    endif
" }

" General {
    :command WQ wq
    :command Wq wq
    :command W w
    :command Q q
    nnoremap <leader>rv :source $MYVIMRC<CR>
    "Scroll Up
    nnoremap <C-e> 10<C-e>
    "Scroll Down
    nnoremap <C-y> 10<C-y>
    "Shortcut
    iabbr sout System.out.println("");
    syntax on                   " Syntax highlighting
    set mouse-=a                " Automatically enable mouse usage
    set mousehide               " Hide the mouse cursor while typing

    "Settings for the line pointed by cursor
    color       default            "Not using fancy solarized
    highlight   clear   SpellBad
    highlight   clear   SignColumn  " SignColumn should match background
    highlight   SpellBad        cterm=underline

    set showmode                    " Display the current mode

    set backspace=indent,eol,start  " Backspace for dummies
    set linespace=0                 " No extra spaces between rows
    set number                      " Line numbers on
    set showmatch                   " Show matching brackets/parenthesis
    set incsearch                   " Find as you type search
    set hlsearch                    " Highlight search terms
    set winminheight=0              " Windows can be 0 line high
    set ignorecase                  " Case insensitive search
    set smartcase                   " Case sensitive when uc present
    set wildmenu                    " Show list instead of just completing
    set wildmode=list:longest,full  " Command <Tab> completion, list matches, then longest common part, then all.
    set whichwrap=b,s,h,l,<,>,[,]   " Backspace and cursor keys wrap too
    set scrolljump=5                " Lines to scroll when cursor leaves screen
    set scrolloff=3                 " Minimum lines to keep above and below cursor
    "set foldenable                  " Auto fold code
    set foldmethod=syntax
    set foldlevel=1
    set foldclose=all
    set list
    set listchars=tab:›\ ,trail:•,extends:#,nbsp:. " Highlight problematic whitespace
    set smartindent
    set autoindent
    set shiftwidth=4
    set tabstop=4
    set softtabstop=4               " Let backspace delete indent
    set expandtab                   " expand tab to spaces
    set wildignore=*.o,*.bak,*.class,*.pyc
    set laststatus=2
    set nolist
    set nojoinspaces                " Prevents inserting two spaces after punctuation on a join (J)
    set splitright                  " Puts new vsplit windows to the right of the current
    set splitbelow                  " Puts new split windows to the bottom of the current
    filetype indent on

    " Most prefer to automatically switch to the current file directory when
    " a new buffer is opened; to prevent this behavior, add the following to
    " your .vimrc.before.local file:
    " let g:no_autochdir = 1
    if !exists('g:no_autochdir')
        autocmd BufEnter * if bufname("") !~ "^\[A-Za-z0-9\]*://" | lcd %:p:h | endif
        " Always switch to the current file directory
    endif

    set shortmess+=filmnrxoOtT          " Abbrev. of messages (avoids 'hit enter')
    set virtualedit=onemore             " Allow for cursor beyond last character
    set history=1000                    " Store a ton of history (default is 20)
    set spell                           " Spell checking on
    set hidden                          " Allow buffer switching without saving

    " Instead of reverting the cursor to the last position in the buffer, we
    " set it to the first line when editing a git commit message
    au FileType gitcommit au! BufEnter COMMIT_EDITMSG call setpos('.', [0, 1, 1, 0])

    " http://vim.wikia.com/wiki/Restore_cursor_to_file_position_in_previous_editing_session
    " Restore cursor to file position in previous editing session
    " To disable this, add the following to your .vimrc.before.local file:
    "   let g:no_restore_cursor = 1
    if !exists('g:no_restore_cursor')
        function! ResCur()
            if line("'\"") <= line("$")
                silent! normal! g`"
                return 1
            endif
        endfunction

        augroup resCur
            autocmd!
            autocmd BufWinEnter * call ResCur()
        augroup END
    endif

    autocmd FileType java set tags=/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/.tags
" }

" functions {
"
	fun! NewJavaFile()
		silent! 0r ~/.vim/templates/java_template
		s/FILENAME/\=expand("%:t:r")/g
	endfun

	autocmd BufNewFile *.java call NewJavaFile()

	fun! NewGoFile()
		silent! 0r ~/.vim/templates/go_template
		s/FILENAME/\=expand("%:t:r")/g
	endfun

	autocmd BufNewFile *.go call NewGoFile()

    fun! NumberToggle()
        if(&relativenumber == 1)
            set norelativenumber
            set number
        else
            set relativenumber
        endif
    endfun

    nnoremap <leader>tn :call NumberToggle()<cr>"

    augroup numbertoggle
        autocmd!
        autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
    augroup END

    fun! TWS()
        let l:save = winsaveview()
        %s/\s\+$//e
        call winrestview(l:save)
    endfun

    " Strip whitespace
    function! StripTrailingWhitespace()
        " Preparation: save last search, and cursor position.
        let _s=@/
        let l = line(".")
        let c = col(".")
        " do the business:
        %s/\s\+$//e
        " clean up: restore previous search history, and cursor position
        let @/=_s
        call cursor(l, c)
    endfunction

    "FZF
    function! FzfOmniFiles()
        let is_git = system('git status')
        if v:shell_error
            :FZFFiles
        else
            :FZFGitFiles
        endif
    endfunction

    function! s:change_branch()
        let res  = system('git checkout ' . a:e)
        :e!
        :python3 powerline.reload()
        echom "Changed Branch to : " . a:e
    endfunction

    command! Gbranch call fzf#run (
        \ {
        \ 'source'  : 'git branch',
        \ 'sink'    : function('<sid>change_branch'),
        \ 'options' : '-m',
        \ 'down'    : '20%'
        \ })
" }

" Mapping {

    :nmap <Tab> gt
    :nmap <s-tab> gT
    noremap j gj
    noremap k gk
    :noremap <Leader>w :call TWS()<CR>
    :imap sout<Tab> System.out.println("");<Esc>F"i

    autocmd FileType c,cpp,java,go,php,javascript,puppet,python,rust,twig,xml,yml,perl,sql autocmd BufWritePre <buffer> if !exists('g:keep_trailing_whitespace') | call TWS() | endif

    " Stupid shift key fixes
    command! -bang -nargs=* -complete=file E e<bang> <args>
    command! -bang -nargs=* -complete=file W w<bang> <args>
    command! -bang -nargs=* -complete=file Wq wq<bang> <args>
    command! -bang -nargs=* -complete=file WQ wq<bang> <args>
    command! -bang Wa wa<bang>
    command! -bang WA wa<bang>
    command! -bang Q q<bang>
    command! -bang QA qa<bang>
    command! -bang Qa qa<bang>

    "Typo correction while opening multiple files
    " Tabe file1 file2 file3
    cmap Tabe tabe

    " Yank from the cursor to the end of the line, to be consistent with C and D.
    nnoremap Y y$

    " Shortcuts
    " Change Working Directory to that of the current file
    cmap cwd lcd %:p:h
    cmap cd. lcd %:p:h

    " Visual shifting (does not exit Visual mode)
    vnoremap < <gv
    vnoremap > >gv

    " Allow using the repeat operator with a visual selection (!)
    " http://stackoverflow.com/a/8064607/127816
    vnoremap . :normal .<CR>

    " For when you forget to sudo.. Really Write the file.
    cmap w!! w !sudo tee % >/dev/null

    " Some helpers to edit mode
    " http://vimcasts.org/e/14
    cnoremap %% <C-R>=fnameescape(expand('%:h')).'/'<cr>
    map <leader>ew :e %%
    map <leader>es :sp %%
    map <leader>ev :vsp %%
    map <leader>et :tabe %%

    " Adjust viewports to the same size
    map <Leader>= <C-w>=

    " Map <Leader>ff to display all lines with keyword under cursor
    " and ask which one to jump to
    nmap <Leader>ff [I:let nr = input("Which one: ")<Bar>exe "normal " . nr ."[\t"<CR>

    " Easier horizontal scrolling
    map zl zL
    map zh zH

    "Make sure LimeLight is turned off while diff
    if &diff
        colorscheme molokai
        "colorscheme evening
    endif
" }


" Plugins {
    " Plugin specific onnfig goes here
    "
    " hardtime {
        nnoremap <leader>h :HardTimeToggle<CR>
        let g:hardtime_timeout = 2000
        let g:hardtime_showmsg = 1
        let g:hardtime_allow_different_key = 1
    " }

    " NerdTree {
        map <C-t> <plug>NERDTreeTabsToggle<CR>
        map <leader>e :NERDTreeFind<CR>
        nmap <leader>nt :NERDTreeFind<CR>

        let NERDTreeShowBookmarks=1
        let NERDTreeIgnore=['\.py[cd]$', '\~$', '\.swo$', '\.swp$', '^\.git$', '^\.hg$', '^\.svn$', '\.bzr$']
        let NERDTreeChDirMode=0
        let NERDTreeQuitOnOpen=1
        let NERDTreeMouseMode=2
        let NERDTreeShowHidden=1
        let NERDTreeKeepTreeInNewTab=1
        let g:nerdtree_tabs_open_on_gui_startup=0
    " }

    " limelight {
        " Color name (:help cterm-colors) or ANSI code
        let g:limelight_conceal_ctermfg = 'gray'
        let g:limelight_conceal_ctermfg = 240

        " Color name (:help gui-colors) or RGB color
        let g:limelight_conceal_guifg = 'DarkGray'
        let g:limelight_conceal_guifg = '#777777'

        " Default: 0.5
        let g:limelight_default_coefficient = 0.7

        " Number of preceding/following paragraphs to include (default: 0)
        let g:limelight_paragraph_span = 5

        " Beginning/end of paragraph
        "   When there's no empty line between the paragraphs
        "   and each paragraph starts with indentation
        let g:limelight_bop = '^\s'
        let g:limelight_eop = '\ze\n^\s'

        " Highlighting priority (default: 10)
        "   Set it to -1 not to overrule hlsearch
        let g:limelight_priority = -1

        autocmd VimEnter * Limelight
        nmap <leader>l :Limelight<CR>
        nmap <leader>nl :Limelight!<CR>
    "}

    "easy-motion {
    "}

    "fzf {
        let g:fzf_command_prefix  = 'FZF'
        " Mapping selecting mappings
        nmap <leader><tab> <plug>(fzf-maps-n)
        xmap <leader><tab> <plug>(fzf-maps-x)
        omap <leader><tab> <plug>(fzf-maps-o)

        " Insert mode completion ( Using YoucompleteMe instead )
        " Used to insert corresponding word/path/file name/ line in the current file at
        " current location
        " from file /usr/share/dict/words
        imap <c-x><c-k> <plug>(fzf-complete-word)
        " Path completion using find (file + dir)
        imap <c-x><c-f> <plug>(fzf-complete-path)
        " File completion using ag
        imap <c-x><c-j> <plug>(fzf-complete-file-ag)
        " Line completion (all open buffers)
        imap <c-x><c-l> <plug>(fzf-complete-line)

        " Display all open files to choose from
        nnoremap <leader>b :FZFBuffers<CR>
        " Code search across all files
        nnoremap <leader>a :FZFAg<CR>
        " Possible commands that can be run on vim command prompt
        nnoremap <leader>; :FZFCommands<CR>
        nnoremap <leader>c :FZFCommits<CR>
        " Jump to a line in the same file
        nnoremap <leader>bl :FZFBLines<CR>
        " Search Files
        nnoremap <Leader>f :call FzfOmniFiles()<CR>
        " tags
        nnoremap <Leader>t :FZFTags<CR>
        nnoremap <Leader>bt :FZFBTags<CR>
     "}

    "Youcompleteme {

        let g:syntastic_java_checkers = []
        let g:EclimFileTypeValidate = 0
        let g:ycm_server_ptyhon_interpreter = ''
        let g:ycm_register_as_syntastic_checker = 1 "default 1
        let g:Show_diagnostics_ui = 1 "default 1

        "will put icons in Vim's gutter on lines that have a diagnostic set.
        "Turning this off will also turn off the YcmErrorLine and YcmWarningLine
        "highlighting
        let g:ycm_enable_diagnostic_signs = 1
        let g:ycm_enable_diagnostic_highlighting = 1
        let g:ycm_always_populate_location_list = 1 "default 0
        let g:ycm_open_loclist_on_ycm_diags = 1 "default 1

        let g:ycm_complete_in_strings = 1 "default 1
        let g:ycm_collect_identifiers_from_tags_files = 0 "default 0
        let g:ycm_path_to_python_interpreter = '' "default ''

        let g:ycm_server_use_vim_stdout = 0 "default 0 (logging to console)
        let g:ycm_server_log_level = 'info' "default info
        let g:ycm_autoclose_preview_window_after_insertion = 1

        nnoremap <c-1> :YcmForceCompileAndDiagnostics<CR>
        nnoremap <Leader>jf :YcmCompleter Format<CR>
        nnoremap <Leader>ji :YcmCompleter OrganizeImports<CR>
        nnoremap <Leader>yr :YcmRestartServer<CR>
    "}
" }

" Unexplored {
    " Easier formatting
   "nnoremap <silent> <leader>q gwip
   ":nnoremap <F5> :buffers<CR>:buffer<Space>
   ":nnoremap <Leader>s :%s/\<<C-r><C-w>\>//g<Left><Left>
    ":hi comment ctermfg=darkcyan
    ":set statusline=%<%F%h%m%r%h%w%y\ %{&ff}\ %{strftime(\"%c\",getftime(expand(\"%:p\")))}%=\ %{'tabn:'.tabpagenr()}\ lin:%l\,%L\ col:%c%V\ pos:%o\ ascii:%b\ %P
    "set background=light
    "
    "
    "if $TMUX == ''
    "    set clipboard+=unnamed
    "else
    "    set clipboard=exclude:.*
    "endif
    "
    "
    "
    "
" }
