#ls command alias
alias ls="ls -hG"
alias ll="ls -lhG"
alias la="ls -ahlG"
alias grep="grep --color"
alias pr="git pull --rebase"
alias rbm="git rebase main"

alias gchk='git checkout $(git branch | fzf)'
alias vim='nvim'

## Setting fd as the default source for fzf
##Only if fd is successfully installed otherwise comment this line
export FD_OPTIONS="--follow --exclude .git --exclude node_modules"
export FZF_DEFAULT_OPTS="--no-mouse --height 40% --multi --tmux center,40% --layout reverse \
    --color=fg+:#000000,bg+:#C0C0C0,hl:#00BFFF,hl+:#DC143C,info:27 
    --border=bold --margin=1 --padding=1  --prompt 'Files >> '  --pointer '>' \
    --walker-skip .git,node_modules,target \
    --header 'CTRL-T: Switch between Files/Directories' \
    --bind 'ctrl-t:transform:[[ ! \$FZF_PROMPT =~ Files ]] &&
          echo \"change-prompt(Files >> )+reload(fd --type file)\" ||
          echo \"change-prompt(Directories >> )+reload(fd --type directory)\"'
          --preview ' [[  \$(file --mime {}) =~ binary  &&  ! \$(file --mime {}) =~ directory ]] &&
              echo {} is a binary file ||
              ([[  \$FZF_PROMPT =~ Files  ]] && bat --color=always {} ||
              [[  \$(file --mime {}) =~ directory  ]] && tree -C {})'"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
export FZF_CTRL_R_OPTS='--sort'
#export FZF_DEFAULT_OPTS="--color=fg+:#000000,bg+:#C0C0C0,hl:#00BFFF,hl+:#DC143C,info:27 --height 40% --border --preview  '(coderay {} || cat {}) 2> /dev/null | head -500'"
export PATH="$PATH:/Users/milindv/gocode"
export FZF_BASE="$HOME/.fzf"
export GREP_OPTIONS='--color=auto'

#fdiff() {
#  preview="git diff $@ --color=always -- {-1}"
#  git diff $@ --name-only | fzf -m --ansi --preview $preview
#}

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
#HYPHEN_INSENSITIVE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
#ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
#COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#plugins=(git
plugins=(zsh-syntax-highlighting
    fzf)

source $ZSH/oh-my-zsh.sh

ZSH_THEME="powerlevel10k/powerlevel10k"

alias glNoGraph='git log --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr% C(auto)%an" "$@"'
_gitLogLineToHash="echo {} | grep -o '[a-f0-9]\{7\}' | head -1"
_viewGitLogLine="$_gitLogLineToHash | xargs -I % sh -c 'git show --color=always % | diff-so-fancy'"

gcop() {
    git log \
        --reverse \
        --color=always  \
        --format="%C(cyan)%h %C(blue)%ar%C(auto)%d \
        %C(yellow)%s%+b %C(black)%ae"  "$@"  |
        fzf -i -e +s \
        --tiebreak=index \
        --no-multi \
        --ansi \
        --border \
        --preview  "$_viewGitLogLine" \
        --header "enter : view C-c : copy hash" \
        --bind "enter:execute:$_viewGitLogLine | less -R" \
        --bind "ctrl-c:execute:$_gitLogLineToHash |
                xclip -r -selection clipboard"
}

source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias nvim-lazy="NVIM_APPNAME=nvim_lazy nvim"
alias nvim-adv="NVIM_APPNAME=nvim_adv nvim"
alias nvim-astro="NVIM_APPNAME=nvim_astro nvim"

function nvims() {
  items=("default" "nvim_lazy" "nvim_adv", "nvim_astro")
  config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)
  if [[ -z $config ]]; then
    echo "Nothing selected"
    return 0
  elif [[ $config == "default" ]]; then
    config=""
  fi
  NVIM_APPNAME=$config nvim $@
}
